name: node js ci cd learning

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
      - name: Build
        run: npm run build
      - name: Copy
        uses: canastro/copy-action@0.0.2
        with:
          source: /home/runner/work/plickee-angular/plickee-angular/dist
          target: /var/www/temp
        
        
