name: node js ci cd learning

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install          
      - name: zip folder
        run: |
          /usr/bin/ng build --prod
          zip -r /var/www/temp/data.zip dist/
          
        
